version: "3"

services:
  app:
    env_file:
      - .env
    build: .
    volumes:
      - .:/django_ecommerce_code
    ports:
      - 8000:8000
    image: motogears_ecommerce:django
    container_name: motogears_django_container
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py loaddata populateDatabase.json && python manage.py runserver 0.0.0.0:8000"
